apiVersion: v1
kind: Service
metadata:
  name: quake
spec:
  type: NodePort
  selector:
    run: quake
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30005
      name: client
    - port: 27960
      targetPort: 27960
      nodePort: 30006
      name: server
    - port: 9090
      targetPort: 9090
      nodePort: 30007
      name: content
